version: '3'
services:
  authentification:
   image: quay.io/keycloak/keycloak:17.0.0
   container_name: authentification
   ports:
     - 8180:8080
   volumes:
     - ./keycloak/data:/var/tmp
     - ./keycloak/startup-scripts/init.sh:/docker-entrypoint-sh/init.sh
   entrypoint: sh -c "/docker-entrypoint-sh/init.sh"
   environment:
    DB_VENDOR:  keycloak
    KEYCLOAK_ADMIN: keycloak
    KEYCLOAK_ADMIN_PASSWORD: keycloak
   networks:
     - theNetwork

  database:
    image: postgres:13
    container_name: database
    restart: always
    ports:
      - 5444:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/config:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    networks:
      - theNetwork

networks:
  theNetwork:
