version: '3.9'
services:
  database:
    image: postgres:13
    container_name: database
    restart: always
    ports:
      - 5444:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/config:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    networks:
      - theNetwork

  npmInstall:
    image: "node:latest"
    working_dir: /home/node/app
    volumes:
      - ../src/main/resources/META-INF/resources:/home/node/app
    command: npm install
    networks:
      - theNetwork

  npmBuild:
    image: "node:latest"
    working_dir: /home/node/app
    depends_on:
      - npmInstall
    volumes:
      - ../src/main/resources/META-INF/resources:/home/node/app
    command: npm exec webpack
    networks:
      - theNetwork

networks:
  theNetwork: