version: '3'
services:
  database:
    image: postgres:13
    container_name: database
    restart: always
    ports:
      - 5444:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/config:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    networks:
      - theNetwork

networks:
  theNetwork:
