version: '3.9'
services:
  database:
    image: postgres:13
    container_name: database
    restart: always
    ports:
      - 5444:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/config:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    networks:
      - theNetwork

networks:
  theNetwork: