version: '3'
services:
  database:
    image: postgres:13
    container_name: database
    restart: always
    ports:
      - 5444:5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
  npmInstall:
    image: "node:latest"
    working_dir: /home/node/app
    volumes:
      - ../src/main/resources/META-INF/resources:/home/node/app
    command: npm install
  npmBuild:
    image: "node:latest"
    working_dir: /home/node/app
    depends_on:
      - npmInstall
    volumes:
      - ../src/main/resources/META-INF/resources:/home/node/app
    command: npm exec webpack
